### ISSUE TITLE
Replace Favicon

### ISSUE THREAD

**Issue by RamiEjailat** [svrnm/DemoMonkey#11]
`<link rel="shortcut icon" type="image/png" href="/images/favicon.png">`
How can I replace the href attribute from /images/favicon.png to https://www.customer.com/theirFavicon.png?

Edit: I was able to do this using the development build https://bit.ly/demomonkey-dev which supports !addScript():
```
$logo = https://www.customer.com/theirFavicon.png
!addScript() = document.querySelector("link[rel*\='icon']").href \= "$logo"\;
```

**Comment by svrnm** [comment]
there is a !querySelector command, the following might work:

```
!querySelector("link[rel*\='icon']", "href") = $logo
```
