### ISSUE TITLE
files delete with each update of Chrome

### ISSUE THREAD

**Issue by jtrivedi83** [svrnm/DemoMonkey#110]
Just updated to Version 108.0.5359.94 (Official Build) (x86_64), and all of the saved mnky files are no longer available. It's like a fresh install. What's the best way to ensure that saved files don't get deleted on each Chrome update?

**Comment by svrnm** [comment]
Hey @jtrivedi83, thanks for raising this issue.

I just did the same and all my configs are still around, can you please let me know the following:

* how did you install DemoMonkey & from witch channel (do you use the stable version from the chrome webstore @ https://bit.ly/demomonkey or any other version)
* Open the DemoMonkey dashboard and in the addressbar replace options.html with backup.html, this will show you a page where you can load your current config, please check if your content is stored there
