### ISSUE TITLE
DemoMonkey no longer changing text in environment

### ISSUE THREAD

**Issue by lcastillo2022** [svrnm/DemoMonkey#13]
I've been using DemoMonkey for years and LOVING IT!!!! All of a sudden it no longer works. Not sure if it has something to do with a new update within Chrome or our environment. We are still using HTML5 so I don't think it has to do with our software. 

I am using the latest version of Chrome, Version 97.0.4692.71 (Official Build) (64-bit)

Any help would be appreciated. Happy to get on a call or send a video or screen shots too if that is helpful.

**Comment by svrnm** [comment]
@lcastillo2022 demo monkey got an update just a few hours ago, so it might be an issue because of that. If you can share more details like videos or screenshots, that would be appreciated. You can send them to me via email (severin.neumann@altmuehlnet.de) or ping me on https://www.presalescollective.com/slack

**Comment by svrnm** [comment]
I found the issue, I pushed a new release to the google chrome webstore, but unfortunately there is no timeline how long it will take them to review and publish (can take hours or days) ... sorry for the inconvenience

**Comment by svrnm** [comment]
What you can do is using the zip file from https://github.com/svrnm/DemoMonkey/releases/download/v8.0.1/DemoMonkey-8.0.1-stable.zip as a "local extension":

* Unzip the file somewhere
* Navigate to chrome://extensions
* Toggle "Developer Mode" at the top right corner
* Click on "Load unpacked"

**Comment by svrnm** [comment]
@lcastillo2022 the new release is on Chrome Webstore, can you check if it works again?
