### ISSUE TITLE
Issues with saving & changing files

### ISSUE THREAD

**Issue by svrnm** [svrnm/DemoMonkey#131]
Since switching from Manifest V2 to Manifest V3, DemoMonkey is experiencing an ongoing issue with storing configurations. We explored multiple options to fix this issue, but none of them worked out.

It looks like the only way to fix this issue is to overhaul the whole the storage mechanism as the current implementation
is not compatible with Manifest V3. This is a huge effort and we need your help to make it happen. If you have bandwidth, experience with JavaScript (and maybe even building Chrome Extensions) and the interest to help, please let us now!

**Comment by clintonfray** [comment]
This issue could be related to the following https://github.com/tshaddix/webext-redux/issues/244#issuecomment-1201650898

**Comment by vladsamoy** [comment]
I have the same issue when changes in the script cannot be saved.
Before browser restart and save button is grayed 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/48059203/222121171-9aa19439-665e-4594-a43e-471ff56eeb62.png">

And after browser restart
<img width="318" alt="image" src="https://user-images.githubusercontent.com/48059203/222121488-87814a55-58be-47e7-a918-89d7e6741ea2.png">

Sometimes it can be saved, but in most cases - not

**Comment by svrnm** [comment]
Please note that we are currently triaging this issue, if you want to help us, please do the following when you encounter the issue the next time:

Open a new browser tab and go to chrome://serviceworker-internals/, you will find a service worker that belongs to demo monkey (scope should be chrome-extension://jgbhioialphpgjgofopnplfibkeehgjd/), please take a screenshot of it details & share it with us, TY!

**Comment by immutafab** [comment]
> Please note that we are currently triaging this issue, if you want to help us, please do the following when you encounter the issue the next time:
> 
> Open a new browser tab and go to chrome://serviceworker-internals/, you will find a service worker that belongs to demo monkey (scope should be chrome-extension://jgbhioialphpgjgofopnplfibkeehgjd/), please take a screenshot of it details & share it with us, TY!
![Screenshot_27](https://github.com/svrnm/DemoMonkey/assets/124327451/55839bb9-e90c-4490-bdcb-e0871b32ca36)

![image](https://github.com/svrnm/DemoMonkey/assets/124327451/741a17ae-f264-4e75-8640-630829b3c3c0)


Here as requested

**Comment by svrnm** [comment]
Thank you @immutafab

**Comment by svrnm** [comment]
This is finally fixed and already shipped in v10.0 :tada:

thank you all for helping!
