### ISSUE TITLE
!setDashboardBackground for Dash studio and FSO demos

### ISSUE THREAD

**Issue by j-sulliman** [svrnm/DemoMonkey#15]
The commands to replace dashboard background and images.  !setDashboardBackground(4932) = https://www.lufthansa.com/content/dam/lh/images/local_images/lufthansa-l-2.jpg.transform/lh-dcep-transform-width-1440/img.jpg
!replaceImage(ad-travel-logo) = https://upload.wikimedia.org/wikipedia/commons/b/b8/Lufthansa_Logo_2018.svg
!recolorDashboard(ad-purple) = midnightblue
!recolorDashboard(ad-cyan) = fdac2a
!recolorDashboard(ad-blue) = midnightblue

Looks like we raised and fixed a bug to get these commands working with Dashstudio also ([https://github.com/Appdynamics/demomonkey/commit/60af9ee26c93eae4a9f2a8bc3d4cd72b6ce2d098#diff-6aa2089b948f23b52b1890[…]caa643477733d5d9e820a43c6845](https://github.com/Appdynamics/demomonkey/commit/60af9ee26c93eae4a9f2a8bc3d4cd72b6ce2d098#diff-6aa2089b948f23b52b1890c11b650fb9f9fbcaa643477733d5d9e820a43c6845)).  But not having any luck with the FSO dashstudio dashboards (i.e. setDashboardBackgrough) .  i.e. AD-Ecrommerce with a dash ID of 879 - !setDashboardBackground(879) = 63D236, doesn't seem to work.  Any suggestions to get above commands working with dash studio appreciated!

**Comment by svrnm** [comment]
is this still relevant?

**Comment by j-sulliman** [comment]
Hi Severin,

Not so much… better for AppD that you focus on all the good stuff you’re doing with OTEL etc :)

Thanks for the follow up.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
