### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vnl** [svrnm/DemoMonkey#16]
**Steps to reproduce:**

1. Clone the repo
2. CD into the repo
3. Run "npm install"

**Expected:**
Install without any errors to build. 

**Actual:** 
The following errors show up. 
`➜  demomonkey git:(main) npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: demomonkey@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.1.1" from react-popup@0.10.0
npm ERR! node_modules/react-popup
npm ERR!   react-popup@"^0.10.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/$user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/$user/.npm/_logs/2022-05-23T13_40_44_869Z-debug-0.log` 

**OS:** macOS Monterey (12.4)
**npm --version:** 8.10.0
**node --version:** 18.1.0

**Comment by svrnm** [comment]
this is fixed.
