### ISSUE TITLE
Indicator for missing site access

### ISSUE THREAD

**Issue by wiswedel** [svrnm/DemoMonkey#17]
In managed browswers, it is possible that certain sites are blocked for extension access. Currently, DemoMonkey does not explicitly indicate that **that** is the apparent reason why no DemoMonkey commands come through.

It would be good if, even though the current URL is included in an activated config and there is no access to the site, the user gets warned about that missing access so the user can expect DemoMonkey not to be working (i.e. there is a problem).

## Background info

Site access properly configured:
![image](https://user-images.githubusercontent.com/1804221/171609988-34646ada-fbe6-46d3-bf8f-1064bc682a1a.png)

Site access _is_ working:
![image](https://user-images.githubusercontent.com/1804221/171609758-6e2f87cf-2eae-4f95-a84b-2ac7e443423e.png)

Site where access is _not_ working:
![image](https://user-images.githubusercontent.com/1804221/171609860-983ea4c0-d701-48a8-b461-424b4ecccb06.png)

**Comment by svrnm** [comment]
You get a small red `!` in the dev-release now, if the page access is not given.

**Comment by svrnm** [comment]
This is part of the stable release already.
