### ISSUE TITLE
JS scripts not firing

### ISSUE THREAD

**Issue by asalustiano** [svrnm/DemoMonkey#178]
Hi Severine,

first, thanks for demo monkey, I used it so much last year. 

For a while now the scripts haven't really been firing when enabled, not sure if someone has reported this before. Similarly, the string replacement have been flaky, sometime it works, some others it doesn't. 

We at Segment really like Demo Monkey and would be happy to support this tools. Let me know how we can help.

Best,
Ana

**Comment by svrnm** [comment]
@asalustiano I will close this now since this might have been related to an ongoing issue that was just recently fixed, please reopen this issue or a new issue if your issue persists
