### ISSUE TITLE
Can we use it standalone without the chrome extension?

### ISSUE THREAD

**Issue by obfusu** [svrnm/DemoMonkey#18]
Hi @svrnm, thanks for developing this plugin!

Could you tell if there is a way to use this plugin as a standalone js embedded in html without the chrome extension?

**Comment by svrnm** [comment]
Hi! not as of now, although this would be a great thing to have. What one would need to do is extracting the monkey.js and make it work outside of the browser context.

**Comment by obfusu** [comment]
got it, thanks 👍
