### ISSUE TITLE
Miro + DemoMonkey

### ISSUE THREAD

**Issue by jm285** [svrnm/DemoMonkey#21]
We have noticed an issue whereby when DemoMonkey is installed into a Chrome profile, it's preventing any Miro boards from loading. Going incognito or removing DemoMonkey enables the Miro board to be loaded again.

This behaviour is happening even when a configuration is not actively loaded. 
![Snip20220831_15](https://user-images.githubusercontent.com/72438005/187638884-68978de6-702c-44fe-bf95-c5c3b6ca4f74.png)

**Comment by svrnm** [comment]
oh, wow, thanks for calling this out, I can reproduce that. Let me check if/how I can fix this quickly.

**Comment by svrnm** [comment]
I found the issue, it seems that the `inline.js` breaks things by importing `JSON5`... I add a small snippet that blocks that code from being loaded if the current URL is miro.com (let's hope there are not that many other pages out there breaking it)

**Comment by jm285** [comment]
Thank you @svrnm ! Is this only in the dev-release or prod version too? (I've still being using the dev-release for the addScript functionality but maybe you rolled this into general now?)

**Comment by svrnm** [comment]
> Thank you @svrnm ! Is this only in the dev-release or prod version too? (I've still being using the dev-release for the addScript functionality but maybe you rolled this into general now?)

It's going into prod soon (I don't have full control over that, because google does checks on the extensions, that can take hours, days or even longer, will keep you posted.)

I can put it in the dev-release as well, there I am currently trying out to get the Manifest V3 working, which is a necessity if I want to keep demo monkey working beyond 2022 :-/

**Comment by svrnm** [comment]
@jm285 it's in the prod version of demomonkey now, can you verify? Also, addScript should also work with the prod version
