### ISSUE TITLE
popup does not have scrollbar

### ISSUE THREAD

**Issue by asmod3us** [svrnm/demomonkey#31]
i have a few demo monkey scripts and with my latest addition this happened:

<img width="456" alt="screen shot 2017-08-01 at 09 05 11" src="https://user-images.githubusercontent.com/450168/28813460-9dd79f42-7699-11e7-8504-d7058b841618.png">

notice that only the upper half of the the last entry is visible.

**Comment by svrnm** [comment]
Have created a fix, check the dev release, if this is also working in your environment:

https://bit.ly/demomonkey-dev

**Comment by asmod3us** [comment]
Thanks, it works, but I think it would be even better if only the bottom view scrolled and the search box would stayed in place: 
<img width="441" alt="screen shot 2017-08-02 at 15 03 57" src="https://user-images.githubusercontent.com/450168/28874888-f860137c-7793-11e7-9216-23d66f108193.png">

Also, despite the scrollbar there's overflow into a second column - not sure if that's intended.

**Comment by svrnm** [comment]
The flow into a second column was my first try to win some space for additional configurations. Will remove it probably. Also the scrolling for only the bottom is useful.

**Comment by svrnm** [comment]
Should be fixed now.

**Comment by svrnm** [comment]
Fixed.
