### ISSUE TITLE
Change text in a span

### ISSUE THREAD

**Issue by laz666** [svrnm/DemoMonkey#51]
Hi,

I have data in a table I would like to edit with demo monkey. Each row in the table is in a span. Is there a way to access this with demo monkey?

The format is:
```
`<div id="g753-side-r0-nx0" class="r0 a1 fs1 f0 ric-grid-row-label ric-grid-row-label--col0 ric-grid-element--alternative-stripes ric-grid-label__fixed-boundary--right ric-grid-row-label--single-line" data-index="0" data-nref="0-0" data-bloodline="RevenueQuota" role="rowheader" aria-selected="false" aria-rowindex="2" aria-colindex="1" style="height: 24px; font-weight: 700;">
<span class="ric-grid-label__content ric-grid-row-label__content">CHANGE THIS TEXT</span>
</div>`
```

**Comment by svrnm** [comment]
hi,

does
```
CHANGE THIS TEXT = my replacement
```

not work?

**Comment by laz666** [comment]
Hi svrnm,

Thanks for the note.

Looks like the table is built with javascript, so the code is not in the base html.

Any way to get around this?

Thanks.

**Comment by svrnm** [comment]
> Looks like the table is built with javascript, so the code is not in the base html.

that should not be an issue, because DemoMonkey is working on the final result. 

To analyse this problem it would be helpful to get some more details, is there a demo monkey config you can share and maybe even a webpage where I can see the problem happening?

**Comment by svrnm** [comment]
@laz666 any more updates on this?
