### ISSUE TITLE
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by clintonfray** [svrnm/DemoMonkey#57]
I've noticed a consistent error in the console relating to a listener. 

There is a listener that is resulting in the error, Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

**Comment by svrnm** [comment]
I saw this one, but I don't see any negative side-effects from it.

**Comment by clintonfray** [comment]
You are correct, I also did not notice an immediate issue with the application although the issue is coming up an an error in the extension.

**Comment by svrnm** [comment]
Looks like the problem is here:

https://github.com/svrnm/DemoMonkey/blob/273df06a60f218cacdfe8147aa5c4c6bc9575b9a/src/background.js#L206

**Comment by svrnm** [comment]
I am not 100% sure if I caught all the potential issues, but at least I don't see it showing up that often anymore

**Comment by clintonfray** [comment]
I will check this as well to see if there is any impact on this.
