### ISSUE TITLE
Content Security Policy error

### ISSUE THREAD

**Issue by clintonfray** [svrnm/DemoMonkey#58]
Clicking on Settings >> Global Variables results in a few errors;

- Content Security Policy error.
- Uncaught DOMException: Failed to execute ‘importScripts’ on ‘WorkerGlobalScope’ (Suspect this is due to the content security policy)

**Comment by svrnm** [comment]
looks like an issue with AceEditor, odd that the same issue does not show up at other places where the editor is used

**Comment by svrnm** [comment]
found it, you can disable the service workers ... not sure for what they are needed, but so far nobody complaint
