### ISSUE TITLE
MUI Components not changing in Dark Mode

### ISSUE THREAD

**Issue by clintonfray** [svrnm/DemoMonkey#93]
## Problem Description
The MUI Components are not changing when transitioning to Dark Mode.

## Example Screenshot
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/74203342/204653917-e8c648f3-fc2a-4591-8690-8a76c9c48cfd.png">

**Comment by svrnm** [comment]
oh... that's a nasty one

**Comment by clintonfray** [comment]
The fix is on it's way, we will be introducing the ThemeProvider for MUI on the main pages.

**Comment by svrnm** [comment]
fixed for now.
